import React from "react";
import "./style.scss";

export default function Footer() {
  return (
    <div
      className="footer"
      data-scroll
    >
   footer
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
   <div>afeaf</div> 
    </div>
  );
}
